#!/bin/sh
echo "Generating build scripts in linphone..."
libtoolize --copy --force
chmod 644 macros/*
cp /opt/gnome2/share/aclocal/gnome2-macros/* macros/.
aclocal-1.6 -I macros
autoheader
automake-1.6 --add-missing --copy
autoconf
rm -rf config.cache

echo "Generating build scripts in osipua..."
cd osipua && ./reconfig

echo "Generating build scripts in oRTP..."
cd ..
cd oRTP && ./reconfig

echo "Generating build scripts in speex..."
cd ..
cd speex && libtoolize --copy --force && aclocal-1.6 && automake-1.6 --add-missing --copy && autoconf -f


