.\" Linphone is an internet phone compatible with the Session Initiation Protocol (SIP: RFC3261 )
.TH "linphone" "1" "1.0.0" "Simon Morlat" "linphone"
.SH "NAME"
.LP 
linphone \- Gnome interface of linphone, a SIP compatible
internet phone.
.SH "SYNTAX"
.LP 
linphone [\fI\-\-help\fP] [\fI\-\-verbose\fP] 

.SH "DESCRIPTION"
.LP 
Linphone can be started without any extra argument. All parameters are accessible from the property box.

.SH "OPTIONS"
.LP 
.TP 
\fB\-\-help\fR
Output help information and exit.
.TP 
\fB\-\-version\fR
Output version information and exit.
\fB\-\-verbose\fR
Output internal messages on stdout, this is useful for debugging.
.SH "FILES"
.LP 
\fI~/.gnome2/linphone\fP 
.br 
This is where linphone reads its config information. You do not have to modify or edit this file.
.br 

.SH "ENVIRONMENT VARIABLES"

.SH "EXAMPLES"

.SH "AUTHORS"
.LP 
Simon MORLAT <simon.morlat@linphone.org>
See the AUTHORS file inside linphone's source for more details.
.SH "SEE ALSO"
.LP 
linphonec(1) sipomatic(1)
