.\" Encoding: ISO-8859-2
.\" Linphone is an internet phone compatible with the Session Initiation Protocol (SIP: RFC3261 )
.\" Translation into Czech by Petr Písaø <petr.pisar@atlas.cz>, 2006-02-26
.TH "linphone" "1" "1.0.0" "Simon Morlat" "linphone"
.do hla cs
.do hpf hyphen.cs
.SH "JMÉNO"
.LP 
linphone \- Gnome rozhraní pro linphone, internetový telefon podporující SIP.
.SH "SYNTAXE"
.LP 
linphone [\fI\-\-help\fP] [\fI\-\-verbose\fP] 

.SH "POPIS"
.LP 
Linphone mù¾e být spu¹tìn bez jakýchkoliv parametrù. V¹echny parametry jsou
mìnitelné v nabídce Nastavení.

.SH "VOLBY"
.LP 
.TP 
\fB\-\-help\fR
Vypí¹e tuto nápovìdu a skonèí.
.TP 
\fB\-\-version\fR
Vypí¹e verzi programu a skonèí.
.TP
\fB\-\-verbose\fR
Na standardní výstup vypisuje vnitøní hlá¹ení programu. Toto je vhodné pøi
ladìní.
.SH "SOUBORY"
.LP 
\fI~/.gnome2/linphone\fP 
.br 
Odtud linphone naèítá svoji konfiguraci. Tento soubor nemusíte mìnit.
.br 

.SH "PROMÌNNÉ PROSTØEDÍ"

.SH "PØÍKLADY"

.SH "AUTOØI"
.LP 
Simon MORLAT <simon.morlat@linphone.org>
Pro podrobnosti nahlédnìte do souboru AUTHORS, který je souèástí zdrojových
kódù linphone.
.SH "VIZ TAKÉ"
.LP 
linphonec(1) sipomatic(1)
